server:
  port: 8080

spring:
  application:
    name: email-sender
  mail:
    host: smtp.gmail.com
    port: 587
    username: example@gmail.com
    password: #################
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true